name: Test

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

  workflow_dispatch:

jobs:
  Test:
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - uses: ./
        with:
          p12-base64: ${{ secrets.CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.CERTIFICATE_PASSWORD }}
